### PR TITLE
Add support for ESP32 boards. Only UART version works for now.

### PR DESCRIPTION
**Pull request by andriyadi**
Hi @whatnick 
This is Andri, the one who discuss with you on Tindie message. As you requested, I create PR, making this library works for ESP32 board. Only UART version works for now. I modified the UART example a bit.
Do let me know if you have concerns. Thanks.

### CODE REVIEW

**Comment by fedy0** [comment]
@andriyadi was this feature tested? And please which esp32 dev board did you use?

@whatnick where you able to successfully test this feature?

Cos I can't get mine to work both (UART and SPI) although I know it's only UART interface is available. 

USED:
Nodemcu-32s board
Arduino IDE 1.8.5

Need support. Thanks in advance

**Comment by whatnick** [comment]
Hi,

Yes this feature is tested works with both UART and SPI. Choose the correct
SPI mode.

Regards,

Tisham.

**Comment by fedy0** [comment]
I meant for esp32. I have tested it with esp8266 and everything works as you described. But not for esp32. None works (both UART and SPI even after changing the SPI settings)

@whatnick
@andriyadi

Please share your ESP32 test setup, settings and code 

Please I really need this support.
Thanks in advance

**Comment by whatnick** [comment]
This code has been tested to work with ESP32 without modification in SPI mode. Choosing SPI pins can be difficult on your particular board. The DIN wemos code here works just fine.https://github.com/whatnick/ATM90E26_SPI_DIN_Wemos/commit/9f590f0211be38dca411565a8ee412ee32ef9c1b

**Pull request merged**
